### ISSUE TITLE
Something went error during deployment:

### ISSUE THREAD

**Issue by chmagitt** [Azure-Samples/e2e-diagnostic-provision-cli#12]
Could you help ?

NPM START

Something went error during deployment:
Error: Entry not found in cache.
    at Logger.createError (C:\IOT\DistributedTracing\e2e-diagnostic-provision-cli\e2e-diagnostic-provision-cli\node_modules\adal-node\lib\log.js:216:13)
    at TokenRequest.<anonymous> (C:\IOT\DistributedTracing\e2e-diagnostic-provision-cli\e2e-diagnostic-provision-cli\node_modules\adal-node\lib\token-request.js:526:40)
    at C:\IOT\DistributedTracing\e2e-diagnostic-provision-cli\e2e-diagnostic-provision-cli\node_modules\adal-node\lib\token-request.js:148:20
    at C:\IOT\DistributedTracing\e2e-diagnostic-provision-cli\e2e-diagnostic-provision-cli\node_modules\adal-node\lib\cache-driver.js:366:7
    at C:\IOT\DistributedTracing\e2e-diagnostic-provision-cli\e2e-diagnostic-provision-cli\node_modules\adal-node\lib\cache-driver.js:301:7
    at Request._callback (C:\IOT\DistributedTracing\e2e-diagnostic-provision-cli\e2e-diagnostic-provision-cli\node_modules\adal-node\lib\util.js:130:7)
    at Request.self.callback (C:\IOT\DistributedTracing\e2e-diagnostic-provision-cli\e2e-diagnostic-provision-cli\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (C:\IOT\DistributedTracing\e2e-diagnostic-provision-cli\e2e-diagnostic-provision-cli\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:198:13)

**Comment by myamama** [comment]
I have the same issue @chmagitt did you manage to fix it?
